### ISSUE TITLE
BoundsError when loading bundle file.

### ISSUE THREAD

**Issue by AnBenLa** [PaulDebus/BundlerIO.jl#12]
@PaulDebus 
The line 
```
n_cams, n_points = readparse(s, Int)
```
seems to produce an BoundsError in some cases.

The load function is called using: 	
```
bundle = load(File(format"OUT", filepath))
```

This problem may be caused by 
``` 
skipmagic(s)
``` 
 behaving strangely in this case.
 
 Maybe the error can be fixed by using 
 
```
inital_line = readparse(s, Int)
while length(inital_line) != 2
      inital_line = readparse(s, Int)
end
n_cams, n_points = inital_line
```
	
instead of 

```
n_cams, n_points = readparse(s, Int)
```

**Comment by PaulDebus** [comment]
In the case of the bundler files I provided, there was a missing space between `n_cams` and `n_points`, so failing was correct, only the error message was not very helpful ;) I fixed this error and the files load fine now. 

I will leave the issue open for now to remind me to fix the error message
